### ISSUE TITLE
the reproduction of results?

### ISSUE THREAD

**Issue by PhysXu** [patchy631/twitter#3]
Hi, thanks for sharing the codes.
I have a simple question:
When I run the codes in **_KMeans_from_scratch.ipynb_**, sometimes I got a strange result, please see below
![image](https://user-images.githubusercontent.com/35793078/222619275-985a3cbe-7fb9-4b04-b2f5-755c17012b8f.png)

How to improve this?

**Comment by patchy631** [comment]
Hi Thanks for trying this out.
KMeans does initialisation of cluster centroids randomly, there is a smarter way called KMeans ++ which i also mentioned in the thread & it's more robust.
I'll be discussing that in future, meanwhile you can find it in the scikit-learn package as a library.
Cheers!
